### ISSUE TITLE
Disscussions moved from issue #8 about problems on CentOS 8

### ISSUE THREAD

**Issue by Gowee** [Gowee/traceroute-map-panel#14]
*cddisk2000 commented 5 days ago:*

> Use Centos 7 Always Fail
>The Main Points Are As Follows

>    Centos 8 Steam or Centos 8
>    The MTR was above 0.94 Offline Install , cannot be used yum
>   I hope Can Help Everyone

*Gowee commented 3 days ago:*

> @ cddisk2000

> Hi.

> I cannot reproduce the problem on a newly installed CentOS Linux release 8.4.2105. What is the version of telegraf and influxdb? Also, I am not sure what do you mean by "Always Fail". Is the telegraf failing to start? Or no data is written to influxdb?

> Would you mind opening an issue where more information can be attached?

*cddisk2000 commented 3 hours ago:*

> @ Gowee
> This is my system environment for your reference
```
    offline install mtr-0.94-2.hs.el8.x86_64.rpm
    Telegraf version 1.19.0
    InfluxDB version: 1.8.6
    CentOS Stream Release 8
    Please confirm that the format must be output using the following command
    mtr -C -n www.google.com
    =======================================================
    Mtr_Version,Start_Time,Status,Host,Hop,Ip,Loss%,Snt, ,Last,Avg,Best,Wrst,StDev,
    MTR.0.94,1624880440,OK,www.google.com,1,192.168.8.254,0.00,10,0,0.24,0.29,0.19,0.41,0.08
    MTR.0.94,1624880440,OK,www.google.com,2,???,100.00,10,10,0.00,0.00,0.00,0.00,0.00
    =======================================================
```

>    If it doesn't work, you can browse my blog,I hope you can succeed
>    https://my-fish-it.blogspot.com/2021/06/ss-grafana-traceroute-map-panel.html

**Comment by Gowee** [comment]
(To keep the discussion seperated from the other issue, I am opening a new issue here.)

@cddisk2000

Hi. I have looked through your blog post where the image shown under "#查詢「mtr」資料表 及前「5」筆資料。" implies the data has already been collected correctly.

I can see only one point displayed on the map in your case. I guess the problem is those `???` in the IP field, which are collected as-is from the output of mtr. `???` usually indicates that the IP address of a hop cannot be determined by mtr, which in turn indicates the hop on the path does not respond to mtr probing.

It is fine to have some `???` hops on a path. But in general, there should be several responding hops. So only one point on the map is abnormal.  

More information are needed to find where the problem is. Is everything working well (at least several non-`???` hops) when you manually mtr via shell? Is the `mtr -C -n www.google.com` output you pasted in the previous issue complete? Or could you please paste the FULL output of `mtr -C -n 8.8.8.8` here?

**Comment by cddisk2000** [comment]
@Gowee 
I'm just doing a sample test , In China Google can't be accessed. If it's other domain names no problem. 
Traceroute map panel is sure to work properly

**Comment by Gowee** [comment]
The [README of mtr](https://github.com/traviscross/mtr) gives concise instructions to install from the source. It should work well on CentOS 7 where I have tested. 

It is also possible to make telegraf adapted to the other output format by tweaking its config as I said in https://github.com/Gowee/traceroute-map-panel/issues/8#issuecomment-804114467.

Feel free to leave comments here if you encounter other problems.

**Comment by cddisk2000** [comment]
@Gowee 
CentOS 7 to install mtr v0.94 from the source succeeded。
Thank you very much

**Comment by Gowee** [comment]
I am happy to hear that.

I will update the README to mention the MTR version requirement.

For better tracking issues, I am going to close this for now. If you have other problems, just reopen it by replying again.
