### ISSUE TITLE
Where do i need to add the Geop Api key ?

### ISSUE THREAD

**Issue by ronzle** [Gowee/traceroute-map-panel#17]
Can you please tel me where i have to add the API key and which is the preferred one ?

I get following error 

The error has been logged in the Debugging Console: TypeError: n.geoIPProviders is undefined

**Comment by Gowee** [comment]
Hi, ronzle.

Thanks for raising the issue.

I guess the problem might be that Grafana breaks some compatibility, again, in newer versions. And the current release of the plugin is only tested on Grafana 7.x. But I am planning to upgrade the plugin to make it work with newer Grafana versions and InfluxDB v2.x.

Could you specify the version of Grafana / InfluxDB you are using?

**Comment by Gowee** [comment]
I am closing the issue for now. Feel free to reply to re-open it if there is still any problem or confusion.
